coverage:
  precision: 2
  round: down
  range: 80..100
  status:
    project:
      default:
        target: 99.5%
        threshold: 0.5%
    patch:
      default:
        target: 99.5%
        threshold: 0.5%
parsers:
  cobertura:
    partials_as_hits: false
